FROM golang:1.25-alpine

WORKDIR /app

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Create necessary directories
RUN mkdir -p /app/assets/image
RUN mkdir -p /app/assets/uploads

# Expose port 8811 to the outside world
EXPOSE 8811

# Command to run the executable
CMD ["air", "-c", ".air.linux.toml"]
